blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_page, name='blog'),
    path('details/<post_id>', views.post_details, name='post-details'),
    path(
        'category/<ctg_name>', views.post_by_category, name='post-by-category'
    )
]

django_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('search/',views.search,name='search'),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('about/', include('about.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('privacy/', views.privacy_policy, name='privacy_policy'),
    path('shipping/', views.shipping_policy, name='shipping_policy'),
    path('return/', views.return_policy, name='return_policy'),
    path('account/', include('account.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

from author.models import AuthorProfile


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='post')
    content = RichTextUploadingField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    author = models.ForeignKey(AuthorProfile, on_delete=models.CASCADE)
    is_draft = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.db.models import Count

from .models import Category, Tag, Post


def blog_page(request):
    post = Post.objects.filter(is_draft=False)
    category = Category.objects.all().annotate(
        number_of_posts=Count('post')
    ).order_by('-number_of_posts', 'name')
    tag = Tag.objects.all()
    recent_post = Post.objects.filter(is_draft=False).order_by('-date')[:3]
    context = {
        'posts': post,
        'categories': category,
        'tags': tag,
        'recent_posts': recent_post
    }
    return render(request, 'blog/blog.html', context)


def post_details(request, post_id):
    post = Post.objects.get(id=post_id)
    category = Category.objects.all().annotate(
        number_of_posts=Count('post')
    ).order_by('-number_of_posts', 'name')
    tag = Tag.objects.all()
    recent_post = Post.objects.filter(is_draft=False).order_by('-date')[:3]
    context = {
        'post': post,
        'categories': category,
        'tags': tag,
        'recent_posts': recent_post
    }
    return render(request, 'blog/post-details.html', context)


def post_by_category(request, ctg_name):
    ctg = Category.objects.get(name=ctg_name)
    post = Post.objects.filter(category=ctg)
    category = Category.objects.all().annotate(
        number_of_posts=Count('post')
    ).order_by('-number_of_posts', 'name')
    tag = Tag.objects.all()
    recent_post = Post.objects.filter(is_draft=False).order_by('-date')[:3]
    context = {
        'posts': post,
        'categories': category,
        'tags': tag,
        'recent_posts': recent_post
    }
    return render(request, 'blog/post-by-category.html', context)

templates/blog/blog.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home</a></span> <span>Blog</span></p>
            <h1 class="mb-0 bread">Blog</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 ftco-animate">
						<div class="row">
              <!-- posts -->
              {% if posts %}
                {% for post in posts %}
    							<div class="col-md-12 d-flex ftco-animate">
    		            <div class="blog-entry align-self-stretch d-md-flex">
    		              <a href="{% url 'post-details' post.id %}" class="block-20" style="background-image: url({{ post.photo.url }});">
    		              </a>
    		              <div class="text d-block pl-md-4">
    		              	<div class="meta mb-3">
    		                  <div><a href="#">{{ post.date }}</a></div>
    		                  <div><a href="#">{{ post.author }}</a></div>
    		                  <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
    		                </div>
    		                <h3 class="heading"><a href="{% url 'post-details' post.id %}">{{ post.title }}</a></h3>
    		                <p>{{ post.content|safe|truncatewords:20 }}</p>
    		                <p><a href="{% url 'post-details' post.id %}" class="btn btn-primary py-2 px-3">Read more</a></p>
    		              </div>
    		            </div>
    		          </div>
                {% endfor %}
              {% else %}
                <h2>There are no Posts in the Database</h2>
              {% endif %}
              <!-- /posts -->
						</div>
          </div> <!-- .col-md-8 -->

          {% include 'blog/sidebar.html' %}

        </div>
      </div>
    </section> <!-- .section -->
{% endblock %}

templates/blog/post-by-category.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home</a></span> <span>Blog</span></p>
            <h1 class="mb-0 bread">Blog</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 ftco-animate">
						<div class="row">
              <!-- posts -->
              {% if posts %}
                {% for post in posts %}
    							<div class="col-md-12 d-flex ftco-animate">
    		            <div class="blog-entry align-self-stretch d-md-flex">
    		              <a href="{% url 'post-details' post.id %}" class="block-20" style="background-image: url({{ post.photo.url }});">
    		              </a>
    		              <div class="text d-block pl-md-4">
    		              	<div class="meta mb-3">
    		                  <div><a href="#">{{ post.date }}</a></div>
    		                  <div><a href="#">{{ post.author }}</a></div>
    		                  <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
    		                </div>
    		                <h3 class="heading"><a href="{% url 'post-details' post.id %}">{{ post.title }}</a></h3>
    		                <p>{{ post.content|safe|truncatewords:20 }}</p>
    		                <p><a href="{% url 'post-details' post.id %}" class="btn btn-primary py-2 px-3">Read more</a></p>
    		              </div>
    		            </div>
    		          </div>
                {% endfor %}
              {% else %}
                <h2>There are no Posts in the Database</h2>
              {% endif %}
              <!-- /posts -->
						</div>
          </div> <!-- .col-md-8 -->

          {% include 'blog/sidebar.html' %}

        </div>
      </div>
    </section> <!-- .section -->
{% endblock %}

templates/blog/post-details.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home</a></span> <span>Blog</span></p>
            <h1 class="mb-0 bread">Blog</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 ftco-animate">
						<h2 class="mb-3">{{ post.title }}</h2>
            <p>{{ post.content|safe }}</p>
            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                {% for tag in post.tag.all %}
                <a href="#" class="tag-cloud-link">{{ tag }}</a>
                {% endfor %}
              </div>
            </div>

            <div class="about-author d-flex p-4 bg-light">
              <div class="bio align-self-md-center mr-4">
                <img src="{{ post.author.photo.url }}" alt="Image placeholder" class="img-fluid mb-4">
              </div>
              <div class="desc align-self-md-center">
                <h3>{{ post.author }}</h3>
                <p>{{ post.author.about }}</p>
              </div>
            </div>


            <div class="pt-5 mt-5">
              <h3 class="mb-5">6 Comments</h3>
              <ul class="comment-list">
                <li class="comment">
                  <div class="vcard bio">
                    <img src="images/person_1.jpg" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>John Doe</h3>
                    <div class="meta">June 27, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply">Reply</a></p>
                  </div>
                </li>

                <li class="comment">
                  <div class="vcard bio">
                    <img src="images/person_1.jpg" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>John Doe</h3>
                    <div class="meta">June 27, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply">Reply</a></p>
                  </div>

                  <ul class="children">
                    <li class="comment">
                      <div class="vcard bio">
                        <img src="images/person_1.jpg" alt="Image placeholder">
                      </div>
                      <div class="comment-body">
                        <h3>John Doe</h3>
                        <div class="meta">June 27, 2018 at 2:21pm</div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                        <p><a href="#" class="reply">Reply</a></p>
                      </div>


                      <ul class="children">
                        <li class="comment">
                          <div class="vcard bio">
                            <img src="images/person_1.jpg" alt="Image placeholder">
                          </div>
                          <div class="comment-body">
                            <h3>John Doe</h3>
                            <div class="meta">June 27, 2018 at 2:21pm</div>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                            <p><a href="#" class="reply">Reply</a></p>
                          </div>

                            <ul class="children">
                              <li class="comment">
                                <div class="vcard bio">
                                  <img src="images/person_1.jpg" alt="Image placeholder">
                                </div>
                                <div class="comment-body">
                                  <h3>John Doe</h3>
                                  <div class="meta">June 27, 2018 at 2:21pm</div>
                                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                  <p><a href="#" class="reply">Reply</a></p>
                                </div>
                              </li>
                            </ul>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </li>

                <li class="comment">
                  <div class="vcard bio">
                    <img src="images/person_1.jpg" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>John Doe</h3>
                    <div class="meta">June 27, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply">Reply</a></p>
                  </div>
                </li>
              </ul>
              <!-- END comment-list -->

              <div class="comment-form-wrap pt-5">
                <h3 class="mb-5">Leave a comment</h3>
                <form action="#" class="p-5 bg-light">
                  <div class="form-group">
                    <label for="name">Name *</label>
                    <input type="text" class="form-control" id="name">
                  </div>
                  <div class="form-group">
                    <label for="email">Email *</label>
                    <input type="email" class="form-control" id="email">
                  </div>
                  <div class="form-group">
                    <label for="website">Website</label>
                    <input type="url" class="form-control" id="website">
                  </div>

                  <div class="form-group">
                    <label for="message">Message</label>
                    <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
                  </div>
                  <div class="form-group">
                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                  </div>

                </form>
              </div>
            </div>
          </div> <!-- .col-md-8 -->
          {% include 'blog/sidebar.html' %}
        </div>
      </div>
    </section> <!-- .section -->
{% endblock %}

templates/blog/sidebar.html
{% load static %}

<div class="col-lg-4 sidebar ftco-animate">
  <div class="sidebar-box">
    <form action="#" class="search-form">
      <div class="form-group">
        <span class="icon ion-ios-search"></span>
        <input type="text" class="form-control" placeholder="Search...">
      </div>
    </form>
  </div>
  <div class="sidebar-box ftco-animate">
    <h3 class="heading">Categories</h3>
    <ul class="categories">
      {% if categories %}
        {% for category in categories %}
        <li><a href="{% url 'post-by-category' category.name %}">{{ category.name }}<span style="color: #000">({{ category.post_set.count }})</span></a></li>
        {% endfor %}
      {% else %}
        <li>There are no Category in the Database</li>
      {% endif %}
    </ul>
  </div>

  <div class="sidebar-box ftco-animate">
    <h3 class="heading">Recent Blog</h3>
    {% if recent_posts %}
      {% for post in recent_posts %}
        <div class="block-21 mb-4 d-flex">
          <a class="blog-img mr-4" style="background-image: url({{ post.photo.url }});"></a>
          <div class="text">
            <h3 class="heading-1"><a href="#">{{ post.title }}</a></h3>
            <div class="meta">
              <div><a href="#"><span class="icon-calendar"></span>{{ post.date }}</a></div>
              <div><a href="#"><span class="icon-person"></span>{{ post.author }}</a></div>
              <div><a href="#"><span class="icon-chat"></span> 19</a></div>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <p>There are no Posts in the Database</p>
    {% endif %}
  </div>

  <div class="sidebar-box ftco-animate">
    <h3 class="heading">Tag Cloud</h3>
    <div class="tagcloud">
      {% if tags %}
        {% for tag in tags %}
        <a href="#" class="tag-cloud-link">{{ tag.name }}</a>
        {% endfor %}
      {% else %}
        <p>There are no Tags in the Database</p>
      {% endif %}
    </div>
  </div>

  <div class="sidebar-box ftco-animate">
    <h3 class="heading">Paragraph</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
  </div>
</div>